logging:
  level:
    com:
      ace:
        dao: DEBUG
  pattern:
    console: ${LOG_LEVEL_PATTERN:-%5p}{magenta} %clr(---){faint} %clr(%-40.40logger{39}){cyan}[%line]%clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}
mapper:
  mappers: com.ace.tk.TKMapper
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ace.entity
  type-handlers-package: com.ace.dao.handler
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
pagehelper:
  helperDialect: mysql
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true
server:
  company: 爱测试
  port: 9001
  servlet:
    context-path: /
    session:
      timeout: 30m
  tomcat:
    uri-encoding: UTF-8
spring:
  banner:
    charset: UTF-8
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat,wall
    initialSize: 5.0
    logSlowSql: true
    maxActive: 20.0
    maxPoolPreparedStatementPerConnectionSize: 20.0
    maxWait: 60000.0
    minEvictableIdleTimeMillis: 300000.0
    minIdle: 5.0
    password: Ace!1228
    poolPreparedStatements: 'true  '
    testOnBorrow: 'false  '
    testOnReturn: 'false  '
    testWhileIdle: 'true  '
    timeBetweenEvictionRunsMillis: 60000.0
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rdsd13n5cbikz7c8y41f0.mysql.rds.aliyuncs.com:3306/ace?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ace
    validationQuery: 'SELECT 1 FROM DUAL'
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    prefix: ''
    request-context-attribute: requestContext
    suffix: .ftl
  mvc:
    static-path-pattern: /**
  redis:
    database: 3
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 10000
        min-idle: 0
      shutdown-timeout: 100
    password: ''
    port: 6379
    timeout: 10000
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
    store-type: redis
web:
  upload-path: resources/